//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorities> Authorities { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TreeOrders> TreeOrders { get; set; }
        public virtual DbSet<Trees> Trees { get; set; }
        public virtual DbSet<TreeTypes> TreeTypes { get; set; }
        public virtual DbSet<UserAuthorities> UserAuthorities { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
